/*
 * This file is generated by jOOQ.
 */
package foodfinder.jooq;


import foodfinder.jooq.tables.Foods;
import foodfinder.jooq.tables.PriceCategories;
import foodfinder.jooq.tables.records.FoodsRecord;
import foodfinder.jooq.tables.records.PriceCategoriesRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<FoodsRecord, Long> IDENTITY_FOODS = Identities0.IDENTITY_FOODS;
    public static final Identity<PriceCategoriesRecord, Long> IDENTITY_PRICE_CATEGORIES = Identities0.IDENTITY_PRICE_CATEGORIES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FoodsRecord> FOODS_PKEY = UniqueKeys0.FOODS_PKEY;
    public static final UniqueKey<PriceCategoriesRecord> PRICE_CATEGORIES_PKEY = UniqueKeys0.PRICE_CATEGORIES_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FoodsRecord, PriceCategoriesRecord> FOODS__FOODS_PRICE_CATEGORY_FKEY = ForeignKeys0.FOODS__FOODS_PRICE_CATEGORY_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<FoodsRecord, Long> IDENTITY_FOODS = Internal.createIdentity(Foods.FOODS, Foods.FOODS.ID);
        public static Identity<PriceCategoriesRecord, Long> IDENTITY_PRICE_CATEGORIES = Internal.createIdentity(PriceCategories.PRICE_CATEGORIES, PriceCategories.PRICE_CATEGORIES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FoodsRecord> FOODS_PKEY = Internal.createUniqueKey(Foods.FOODS, "foods_pkey", new TableField[] { Foods.FOODS.ID }, true);
        public static final UniqueKey<PriceCategoriesRecord> PRICE_CATEGORIES_PKEY = Internal.createUniqueKey(PriceCategories.PRICE_CATEGORIES, "price_categories_pkey", new TableField[] { PriceCategories.PRICE_CATEGORIES.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<FoodsRecord, PriceCategoriesRecord> FOODS__FOODS_PRICE_CATEGORY_FKEY = Internal.createForeignKey(Keys.PRICE_CATEGORIES_PKEY, Foods.FOODS, "foods_price_category_fkey", new TableField[] { Foods.FOODS.PRICE_CATEGORY }, true);
    }
}
