/*
 * This file is generated by jOOQ.
 */
package foodfinder.jooq;


import foodfinder.jooq.tables.Foods;
import foodfinder.jooq.tables.PriceCategories;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 295128417;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.foods</code>.
     */
    public final Foods FOODS = Foods.FOODS;

    /**
     * The table <code>public.price_categories</code>.
     */
    public final PriceCategories PRICE_CATEGORIES = PriceCategories.PRICE_CATEGORIES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.FOODS_ID_SEQ,
            Sequences.PRICE_CATEGORIES_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Foods.FOODS,
            PriceCategories.PRICE_CATEGORIES);
    }
}
