/*
 * This file is generated by jOOQ.
 */
package foodfinder.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.foods_id_seq</code>
     */
    public static final Sequence<Long> FOODS_ID_SEQ = Internal.createSequence("foods_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.price_categories_id_seq</code>
     */
    public static final Sequence<Long> PRICE_CATEGORIES_ID_SEQ = Internal.createSequence("price_categories_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
