/*
 * This file is generated by jOOQ.
 */
package foodfinder.jooq;


import foodfinder.jooq.tables.Foods;
import foodfinder.jooq.tables.PriceCategories;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.foods</code>.
     */
    public static final Foods FOODS = Foods.FOODS;

    /**
     * The table <code>public.price_categories</code>.
     */
    public static final PriceCategories PRICE_CATEGORIES = PriceCategories.PRICE_CATEGORIES;
}
